### ISSUE TITLE
Build instructions

### ISSUE THREAD

**Issue by thisni1s** [zoomyboy/adrema#1]
Hi,
die Bilder und Feature beschreibungen sehen ja echt gut aus 👍
Vielleicht könntest du im README noch reinschrieben wie man das ganze laufen lässt. Ein einfaches ```docker-compose build``` schlägt bei mir fehl, selbst wenn ich den richtigen Pfad zur Dockerfile eintrage.

**Comment by zoomyboy** [comment]
Jo, die docker env ist etwas veraltet. Werde ich beizeiten korrigieren.

**Comment by zoomyboy** [comment]
Sollte nun klappen. Build instructions stehen in der README

**Comment by superaffectivejosh** [comment]
I agree!
